### ISSUE TITLE
Local qr code image not scanning

### ISSUE THREAD

**Issue by 0xS4N4TG** [nikolaDrljaca/bitcodept#2]
Hi, Today i updated the app and tried to scan the local qr code image of a wifi network,the app just hung and when i clicked the screen the saving code loader disappeared and image did not saved neither gave me the information, i have tried it multiple times but same thing happens.please fix this issue.

thanks

**Comment by nikolaDrljaca** [comment]
Thank you for bringing it up. Wifi codes are not yet supported. I will be working on the issue immediately.

**Comment by 0xS4N4TG** [comment]
Ok thanks
